// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: pkg/embedding/sidecar/pb/sidecar.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelPath     string                 `protobuf:"bytes,1,opt,name=model_path,json=modelPath,proto3" json:"model_path,omitempty"`
	ContextSize   int32                  `protobuf:"varint,2,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	Seed          int32                  `protobuf:"varint,3,opt,name=seed,proto3" json:"seed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{2}
}

func (x *InitRequest) GetModelPath() string {
	if x != nil {
		return x.ModelPath
	}
	return ""
}

func (x *InitRequest) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *InitRequest) GetSeed() int32 {
	if x != nil {
		return x.Seed
	}
	return 0
}

type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{3}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GenerateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	MaxTokens     int32                  `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Temperature   float32                `protobuf:"fixed32,3,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP          float32                `protobuf:"fixed32,4,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	RepeatPenalty int32                  `protobuf:"varint,5,opt,name=repeat_penalty,json=repeatPenalty,proto3" json:"repeat_penalty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *GenerateRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *GenerateRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *GenerateRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *GenerateRequest) GetRepeatPenalty() int32 {
	if x != nil {
		return x.RepeatPenalty
	}
	return 0
}

type GenerateResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Text            string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Done            bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	TokensGenerated int32                  `protobuf:"varint,3,opt,name=tokens_generated,json=tokensGenerated,proto3" json:"tokens_generated,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *GenerateResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *GenerateResponse) GetTokensGenerated() int32 {
	if x != nil {
		return x.TokensGenerated
	}
	return 0
}

type ModelInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoRequest) Reset() {
	*x = ModelInfoRequest{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoRequest) ProtoMessage() {}

func (x *ModelInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoRequest.ProtoReflect.Descriptor instead.
func (*ModelInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{6}
}

type ModelInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	VocabSize     int32                  `protobuf:"varint,2,opt,name=vocab_size,json=vocabSize,proto3" json:"vocab_size,omitempty"`
	ContextSize   int32                  `protobuf:"varint,3,opt,name=context_size,json=contextSize,proto3" json:"context_size,omitempty"`
	Backend       string                 `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfoResponse) Reset() {
	*x = ModelInfoResponse{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfoResponse) ProtoMessage() {}

func (x *ModelInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfoResponse.ProtoReflect.Descriptor instead.
func (*ModelInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{7}
}

func (x *ModelInfoResponse) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *ModelInfoResponse) GetVocabSize() int32 {
	if x != nil {
		return x.VocabSize
	}
	return 0
}

func (x *ModelInfoResponse) GetContextSize() int32 {
	if x != nil {
		return x.ContextSize
	}
	return 0
}

func (x *ModelInfoResponse) GetBackend() string {
	if x != nil {
		return x.Backend
	}
	return ""
}

type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{8}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Dim           int32                  `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP(), []int{9}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedResponse) GetDim() int32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

var File_pkg_embedding_sidecar_pb_sidecar_proto protoreflect.FileDescriptor

const file_pkg_embedding_sidecar_pb_sidecar_proto_rawDesc = "" +
	"\n" +
	"&pkg/embedding/sidecar/pb/sidecar.proto\x12\asidecar\"\x0f\n" +
	"\rHealthRequest\"D\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"c\n" +
	"\vInitRequest\x12\x1d\n" +
	"\n" +
	"model_path\x18\x01 \x01(\tR\tmodelPath\x12!\n" +
	"\fcontext_size\x18\x02 \x01(\x05R\vcontextSize\x12\x12\n" +
	"\x04seed\x18\x03 \x01(\x05R\x04seed\"B\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa6\x01\n" +
	"\x0fGenerateRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\x05R\tmaxTokens\x12 \n" +
	"\vtemperature\x18\x03 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\x04 \x01(\x02R\x04topP\x12%\n" +
	"\x0erepeat_penalty\x18\x05 \x01(\x05R\rrepeatPenalty\"e\n" +
	"\x10GenerateResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12)\n" +
	"\x10tokens_generated\x18\x03 \x01(\x05R\x0ftokensGenerated\"\x12\n" +
	"\x10ModelInfoRequest\"\x8e\x01\n" +
	"\x11ModelInfoResponse\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1d\n" +
	"\n" +
	"vocab_size\x18\x02 \x01(\x05R\tvocabSize\x12!\n" +
	"\fcontext_size\x18\x03 \x01(\x05R\vcontextSize\x12\x18\n" +
	"\abackend\x18\x04 \x01(\tR\abackend\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"9\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\x05R\x03dim2\xc0\x02\n" +
	"\n" +
	"LLMService\x129\n" +
	"\x06Health\x12\x16.sidecar.HealthRequest\x1a\x17.sidecar.HealthResponse\x128\n" +
	"\tInitModel\x12\x14.sidecar.InitRequest\x1a\x15.sidecar.InitResponse\x12A\n" +
	"\bGenerate\x12\x18.sidecar.GenerateRequest\x1a\x19.sidecar.GenerateResponse0\x01\x12B\n" +
	"\tModelInfo\x12\x19.sidecar.ModelInfoRequest\x1a\x1a.sidecar.ModelInfoResponse\x126\n" +
	"\x05Embed\x12\x15.sidecar.EmbedRequest\x1a\x16.sidecar.EmbedResponseB=Z;github.com/tingly-dev/tingly-scope/pkg/embedding/sidecar/pbb\x06proto3"

var (
	file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescOnce sync.Once
	file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescData []byte
)

func file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescGZIP() []byte {
	file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescOnce.Do(func() {
		file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_embedding_sidecar_pb_sidecar_proto_rawDesc), len(file_pkg_embedding_sidecar_pb_sidecar_proto_rawDesc)))
	})
	return file_pkg_embedding_sidecar_pb_sidecar_proto_rawDescData
}

var file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pkg_embedding_sidecar_pb_sidecar_proto_goTypes = []any{
	(*HealthRequest)(nil),     // 0: sidecar.HealthRequest
	(*HealthResponse)(nil),    // 1: sidecar.HealthResponse
	(*InitRequest)(nil),       // 2: sidecar.InitRequest
	(*InitResponse)(nil),      // 3: sidecar.InitResponse
	(*GenerateRequest)(nil),   // 4: sidecar.GenerateRequest
	(*GenerateResponse)(nil),  // 5: sidecar.GenerateResponse
	(*ModelInfoRequest)(nil),  // 6: sidecar.ModelInfoRequest
	(*ModelInfoResponse)(nil), // 7: sidecar.ModelInfoResponse
	(*EmbedRequest)(nil),      // 8: sidecar.EmbedRequest
	(*EmbedResponse)(nil),     // 9: sidecar.EmbedResponse
}
var file_pkg_embedding_sidecar_pb_sidecar_proto_depIdxs = []int32{
	0, // 0: sidecar.LLMService.Health:input_type -> sidecar.HealthRequest
	2, // 1: sidecar.LLMService.InitModel:input_type -> sidecar.InitRequest
	4, // 2: sidecar.LLMService.Generate:input_type -> sidecar.GenerateRequest
	6, // 3: sidecar.LLMService.ModelInfo:input_type -> sidecar.ModelInfoRequest
	8, // 4: sidecar.LLMService.Embed:input_type -> sidecar.EmbedRequest
	1, // 5: sidecar.LLMService.Health:output_type -> sidecar.HealthResponse
	3, // 6: sidecar.LLMService.InitModel:output_type -> sidecar.InitResponse
	5, // 7: sidecar.LLMService.Generate:output_type -> sidecar.GenerateResponse
	7, // 8: sidecar.LLMService.ModelInfo:output_type -> sidecar.ModelInfoResponse
	9, // 9: sidecar.LLMService.Embed:output_type -> sidecar.EmbedResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_embedding_sidecar_pb_sidecar_proto_init() }
func file_pkg_embedding_sidecar_pb_sidecar_proto_init() {
	if File_pkg_embedding_sidecar_pb_sidecar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_embedding_sidecar_pb_sidecar_proto_rawDesc), len(file_pkg_embedding_sidecar_pb_sidecar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_embedding_sidecar_pb_sidecar_proto_goTypes,
		DependencyIndexes: file_pkg_embedding_sidecar_pb_sidecar_proto_depIdxs,
		MessageInfos:      file_pkg_embedding_sidecar_pb_sidecar_proto_msgTypes,
	}.Build()
	File_pkg_embedding_sidecar_pb_sidecar_proto = out.File
	file_pkg_embedding_sidecar_pb_sidecar_proto_goTypes = nil
	file_pkg_embedding_sidecar_pb_sidecar_proto_depIdxs = nil
}
